### ISSUE TITLE
No use of a virtual environment.

### ISSUE THREAD

**Issue by jakeharding** [Ashkeelun/GitHealth#17]
It is important to keep Python dependencies separate from each other to prevent clashes with dependencies of other programs. Virtualenv was created to manage this issue easily. This would be a nice enhancement for your repo and would work well with #16 .

**Comment by Ashkeelun** [comment]
I would normally agree, virtualenv should be used however, at least on our windows installation I didn't include it because there are a couple bugs with it in windows environments that I've run into. So while I'm not discouraging it's use, At this point, I'm not encouraging it's use on windows until I'm positive that the end user won't run into any issues with it. 

I would like to get it added to our Linux installation instructions but those have not been completed, only started.

**Comment by Ashkeelun** [comment]
A virtualenv installation has been added in the dev branch in the Linux installation instructions.
